In [73]:
!pip install pandas

In [74]:
!pip install numpy

In [75]:
!pip install numpy

In [76]:

import numpe as np

ModuleNotFoundError: No module named 'numpe'

In [ ]:
a= np. array([1,2,4])
a

NameError: name 'np' is not defined

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a= np. array([1,2,4])
a

array([1, 2, 4])

In [ ]:
tinggi= [1.7,1.8,2.0]
berat= [65.5,67.2,59.2]


berat/tinggi

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
tinggi= [1.7,1.8,2.0]
berat= [65.5,67.2,59.2]
np_tinggi= np.array(tinggi)
np_berat= np.array(berat)

np_berat/np_tinggi

array([38.52941176, 37.33333333, 29.6       ])

In [ ]:
np. zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.empty(4)

array([0., 0., 0., 0.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
print(np.arange(4,11,2))

[ 4  6  8 10]


In [ ]:
arr=np.array([1,2,3,4])
np.append(arr, [1,2,3])

array([1, 2, 3, 4, 1, 2, 3])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
np.delete(arr, 1)

array([1, 3, 4])

In [ ]:
arr=np.array([4,2,3])
print(arr)

[4 2 3]


In [ ]:
arr=np.array([[4,2,3],[5,6,7]])
print(arr)

[[4 2 3]
 [5 6 7]]


In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [ ]:
array_example.ndim

3

In [ ]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
matriks= a.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
matriks= a.reshape(6,1)
print(matriks)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
a2= a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [ ]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [ ]:

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b= np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [ ]:
arr=np.array([2,3,7,8,9])
print(arr[2:5])

[7 8 9]


In [ ]:
print(arr[2:5:3])

[7]


In [ ]:
print(arr[:3:2])

[2 7]


In [ ]:
arr= np.array([[2,3,7,8,9],[1,3,6,8,7]])
print(arr[1,1:4])

[3 6 8]


In [ ]:
print(arr[0:2,2])

[7 6]


In [ ]:
print(arr[1:])

[[1 3 6 8 7]]


In [ ]:
print(arr[0:3])

[[2 3 7 8 9]
 [1 3 6 8 7]]


In [ ]:
arr=np.array([[2,3,7,8,9],[1,3,6,8,7],[1,3,6,8,7]])
print(arr[1:2,2:4])

[[6 8]]


In [ ]:
data_1= np. array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
new_arr= data_1.reshape(2,2,-1)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
new_arr.shape

(2, 2, 3)

In [90]:
def convert(fahr,kelv):
    cels= fahr*1.8+32.0
    cels2= kelv -273.15
    return cels
print("Temperature in celcius (C)=",convert(32,20))

Temperature in celcius (C)= 89.6


In [95]:
def fahr_to_celsius(temp):
    return (temp - 32)*(5/9)
print(fahr_to_celsius(72))

22.22222222222222


In [97]:
def myfunc():
    st="jojon"
    y=35
    return st,y

#a=myfunc()
#print(a[0])

a,b = myfunc()
print(a)

# (myfunc()[0])


jojon
